services:
  baby-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baby-app
    ports:
      - "8000:8000"
    environment:
      - TURSO_DB_NAME=${TURSO_DB_NAME:-babyapp-yingyingpeng1122}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"